dependencies:
 - name: binderhub
   # NOTE: when binderhub version is upgraded, upgrade chart version too (Chart.yaml)
   version: 0.2.0-n465.hb35ec4e
   repository: https://jupyterhub.github.io/helm-chart
