kind: ConfigMap
apiVersion: v1
metadata:
  name: persistent-bhub-templates
  labels: { { - include "persistent_binderhub.configmap_labels" . | indent 4 } }
data:
  { { - (.Files.Glob "files/jupyterhub/templates/*").AsConfig | nindent 2 } }
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: persistent-bhub-statics
  labels: { { - include "persistent_binderhub.configmap_labels" . | indent 4 } }
data: { { - (.Files.Glob "files/jupyterhub/statics/*").AsConfig | nindent 2 } }
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: persistent-bhub-config
  labels: { { - include "persistent_binderhub.configmap_labels" . | indent 4 } }
data:
  persistent_bhub_config.py: |-
    {{- .Files.Get "files/jupyterhub/persistent_bhub_config.py" | nindent 4 }}
